name: CreateRelease

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup
      id: GetVersion
      run: |
        VT_VERSION=$(grep -m1 VT_VERSION vesc_tool.pro  | awk -F= '{ print $2 }' | sed 's/[ ",]//g')
        echo ::set-output name=VERSION::${VT_VERSION}
    - name: CreateRelease
      env:
        GITHUB_TOKEN: ${{ secrets.VT_CR_TOKEN }}
      uses: darwinbeing/create-release@master
      with:
        tag_name: ${{ steps.GetVersion.outputs.VERSION }}
        release_name: Release ${{ steps.GetVersion.outputs.VERSION }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false



