name: CreateTag

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      id: GetVersion
      run: |
        VT_VERSION=$(grep -m1 VT_VERSION vesc_tool.pro  | awk -F= '{ print $2 }' | sed 's/[ ",]//g')
        VT_VERSION=2.03
        echo ::set-output name=VERSION::${VT_VERSION}
    - name: CreateTag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/create-release@v1.0.0
      with:
        tag_name: ${{ steps.GetVersion.outputs.VERSION }}
        release_name: Release ${{ steps.GetVersion.outputs.VERSION }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false



